name: Deploy MultiDocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
      - run: docker build -t pablorodriguez88/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true pablorodriguez88/react-test npm test

      - run: docker build -t pablorodriguez88/multi-client ./client
      - run: docker build -t pablorodriguez88/multi-nginx ./nginx
      - run: docker build -t pablorodriguez88/multi-server ./server
      - run: docker build -t pablorodriguez88/multi-worker ./worker

      - run: docker push pablorodriguez88/multi-client
      - run: docker push pablorodriguez88/multi-nginx
      - run: docker push pablorodriguez88/multi-server
      - run: docker push pablorodriguez88/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name:
          environment_name:
          existing_bucket_name:
          region:
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
